# Generated by Django 6.1.1 on 2026-09-26 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PembelianCabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=150)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('nama_barang', models.CharField(max_length=255)),
                ('deskripsi_fungsi_peruntukan', models.TextField()),
                ('estimasi_harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referensi', models.CharField(blank=True, help_text='Link atau info toko', max_length=255)),
                ('upload_foto', models.ImageField(upload_to='pembelian/referensi/')),
                ('keterangan_sam', models.TextField(blank=True, null=True)),
                ('is_approved_sam', models.BooleanField(blank=True, null=True)),
                ('keterangan_sm', models.TextField(blank=True, null=True)),
                ('is_approved_sm', models.BooleanField(blank=True, null=True)),
                ('status_approval', models.CharField(choices=[('WAITING_SAM', 'Menunggu Approval SAM'), ('WAITING_SM', 'Menunggu Approval SM'), ('APPROVED_TO_GA', 'Disetujui (Diteruskan ke GA)'), ('REJECTED_SAM', 'Ditolak SAM (NOK)'), ('REJECTED_SM', 'Ditolak SM (NOK)')], default='WAITING_SAM', max_length=30)),
                ('tahapan_ga', models.CharField(choices=[('PENDING', 'Pending Belum Diproses'), ('SEARCH', 'Search'), ('BOUGHT', 'Bought (Dibeli)'), ('SHIPPED', 'Shipped (Dikirim)'), ('ARRIVED', 'Arrived (Tiba)'), ('HANDOVER', 'Handover (Selesai/Diserahkan)')], default='PENDING', max_length=20)),
                ('nomor_invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_invoice', models.FileField(blank=True, null=True, upload_to='pembelian/invoice/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembelian_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerbaikanJasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=150)),
                ('divisi', models.CharField(max_length=50)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('lokasi_spesifik', models.CharField(max_length=255)),
                ('objek', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('upload_foto', models.ImageField(upload_to='perbaikan/laporan/')),
                ('deskripsi_kebutuhan_bahan', models.TextField(blank=True, null=True)),
                ('estimasi_harga', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('urgensi', models.CharField(blank=True, choices=[('EMERGENCY', 'Emergency'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('PLANNED', 'Planned')], max_length=20, null=True)),
                ('alasan_nok_sam', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WAITING_GA', 'Menunggu Estimasi GA'), ('WAITING_SAM', 'Menunggu Review SAM'), ('APPROVED', 'Disetujui (Diteruskan ke Teknisi)'), ('REJECTED', 'Ditolak (NOK)')], default='WAITING_GA', max_length=30)),
                ('progress_pekerjaan', models.CharField(choices=[('BELUM DIKERJAKAN', 'Belum Dikerjakan'), ('PROSES', 'Proses'), ('SELESAI', 'Selesai')], default='BELUM DIKERJAKAN', max_length=30)),
                ('kendala', models.TextField(blank=True, null=True)),
                ('foto_hasil_pekerjaan', models.ImageField(blank=True, null=True, upload_to='perbaikan/selesai/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perbaikan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('USER', 'User Divisi'), ('GA', 'General Affair (GA)'), ('SAM', 'SAM'), ('SM', 'Store Manager (SM)'), ('TEKNISI', 'Teknisi')], default='USER', max_length=20)),
                ('divisi', models.CharField(choices=[('SM', 'SM'), ('BO', 'BO'), ('MS', 'MS'), ('FOOD', 'FOOD'), ('NON FOOD', 'NON FOOD'), ('PERISH', 'PERISH'), ('LOG 1', 'LOG 1'), ('LOG 2', 'LOG 2'), ('GA', 'GA'), ('TEKNISI', 'TEKNISI')], default='BO', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
