# Generated by Django 6.1.1 on 2026-09-26 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembeliancabang',
            name='deskripsi_fungsi_peruntukan',
        ),
        migrations.RemoveField(
            model_name='pembeliancabang',
            name='estimasi_harga',
        ),
        migrations.RemoveField(
            model_name='pembeliancabang',
            name='nama_barang',
        ),
        migrations.RemoveField(
            model_name='pembeliancabang',
            name='referensi',
        ),
        migrations.RemoveField(
            model_name='pembeliancabang',
            name='upload_foto',
        ),
        migrations.CreateModel(
            name='ItemPembelianCabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('deskripsi_fungsi_peruntukan', models.TextField()),
                ('estimasi_harga', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referensi', models.CharField(blank=True, help_text='Link atau info toko', max_length=255)),
                ('upload_foto', models.ImageField(blank=True, null=True, upload_to='pembelian/referensi/')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pembeliancabang')),
            ],
        ),
    ]
