# Generated by Django 6.1.1 on 2026-09-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pembeliancabang_deskripsi_fungsi_peruntukan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembeliancabang',
            name='no_dokumen',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perbaikanjasa',
            name='no_dokumen',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pembeliancabang',
            name='tahapan_ga',
            field=models.CharField(choices=[('PENDING', 'Pending Belum Diproses'), ('SEARCH', 'Dicari Toko / Vendor'), ('BOUGHT', 'Dibeli'), ('SHIPPED', 'Dikirim'), ('ARRIVED', 'Tiba'), ('HANDOVER', 'Handover (Selesai/Diserahkan)')], default='PENDING', max_length=20),
        ),
    ]
