# Generated by Django 6.1.1 on 2026-10-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pembeliancabang_no_dokumen_perbaikanjasa_no_dokumen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nomor_hp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor HP/WhatsApp'),
        ),
    ]
